// Code generated by protoc-gen-go. DO NOT EDIT.
// source: tool.proto

package pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type DbInfo struct {
	Name     string `protobuf:"bytes,1,opt,name=name" json:"name"`
	Ip       string `protobuf:"bytes,2,opt,name=ip" json:"ip"`
	Port     int32  `protobuf:"varint,3,opt,name=port" json:"port"`
	UserName string `protobuf:"bytes,4,opt,name=userName" json:"userName"`
	Password string `protobuf:"bytes,5,opt,name=password" json:"password"`
	Id       int64  `protobuf:"varint,6,opt,name=id" json:"id"`
}

func (m *DbInfo) Reset()                    { *m = DbInfo{} }
func (m *DbInfo) String() string            { return proto.CompactTextString(m) }
func (*DbInfo) ProtoMessage()               {}
func (*DbInfo) Descriptor() ([]byte, []int) { return fileDescriptor4, []int{0} }

func (m *DbInfo) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *DbInfo) GetIp() string {
	if m != nil {
		return m.Ip
	}
	return ""
}

func (m *DbInfo) GetPort() int32 {
	if m != nil {
		return m.Port
	}
	return 0
}

func (m *DbInfo) GetUserName() string {
	if m != nil {
		return m.UserName
	}
	return ""
}

func (m *DbInfo) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *DbInfo) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

// 创建数据库
type CreateOrModifyReq struct {
	Db *DbInfo `protobuf:"bytes,1,opt,name=db" json:"db"`
}

func (m *CreateOrModifyReq) Reset()                    { *m = CreateOrModifyReq{} }
func (m *CreateOrModifyReq) String() string            { return proto.CompactTextString(m) }
func (*CreateOrModifyReq) ProtoMessage()               {}
func (*CreateOrModifyReq) Descriptor() ([]byte, []int) { return fileDescriptor4, []int{1} }

func (m *CreateOrModifyReq) GetDb() *DbInfo {
	if m != nil {
		return m.Db
	}
	return nil
}

// 创建数据库
type CreateOrModifyRsp struct {
}

func (m *CreateOrModifyRsp) Reset()                    { *m = CreateOrModifyRsp{} }
func (m *CreateOrModifyRsp) String() string            { return proto.CompactTextString(m) }
func (*CreateOrModifyRsp) ProtoMessage()               {}
func (*CreateOrModifyRsp) Descriptor() ([]byte, []int) { return fileDescriptor4, []int{2} }

func init() {
	proto.RegisterType((*DbInfo)(nil), "pb.DbInfo")
	proto.RegisterType((*CreateOrModifyReq)(nil), "pb.CreateOrModifyReq")
	proto.RegisterType((*CreateOrModifyRsp)(nil), "pb.CreateOrModifyRsp")
}

func init() { proto.RegisterFile("tool.proto", fileDescriptor4) }

var fileDescriptor4 = []byte{
	// 192 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x4f, 0xcd, 0xca, 0xc2, 0x30,
	0x10, 0x24, 0xe9, 0x0f, 0xdf, 0xb7, 0x1f, 0x7c, 0x60, 0xbc, 0x84, 0x9e, 0x4a, 0x4f, 0x3d, 0x55,
	0xd0, 0x47, 0xd0, 0x8b, 0x07, 0x15, 0xf2, 0x06, 0x0d, 0x49, 0x21, 0xa0, 0xdd, 0x35, 0x89, 0x88,
	0x6f, 0xe0, 0x63, 0x4b, 0x53, 0xf4, 0xe2, 0x6d, 0x66, 0x67, 0x66, 0x99, 0x01, 0x88, 0x88, 0xe7,
	0x8e, 0x3c, 0x46, 0x14, 0x9c, 0x74, 0xf3, 0x64, 0x50, 0xee, 0xf4, 0x7e, 0x1c, 0x50, 0x08, 0xc8,
	0xc7, 0xfe, 0x62, 0x25, 0xab, 0x59, 0xfb, 0xab, 0x12, 0x16, 0xff, 0xc0, 0x1d, 0x49, 0x9e, 0x2e,
	0xdc, 0xd1, 0xe4, 0x21, 0xf4, 0x51, 0x66, 0x35, 0x6b, 0x0b, 0x95, 0xb0, 0xa8, 0xe0, 0xe7, 0x16,
	0xac, 0x3f, 0x4e, 0xd9, 0x3c, 0x39, 0x3f, 0x7c, 0xd2, 0xa8, 0x0f, 0xe1, 0x8e, 0xde, 0xc8, 0x62,
	0xd6, 0xde, 0x3c, 0xfd, 0x36, 0xb2, 0xac, 0x59, 0x9b, 0x29, 0xee, 0x4c, 0xb3, 0x82, 0xc5, 0xd6,
	0xdb, 0x3e, 0xda, 0x93, 0x3f, 0xa0, 0x71, 0xc3, 0x43, 0xd9, 0xab, 0xa8, 0x80, 0x1b, 0x9d, 0x2a,
	0xfd, 0xad, 0xa1, 0x23, 0xdd, 0xcd, 0x65, 0x15, 0x37, 0xba, 0x59, 0x7e, 0x05, 0x02, 0xe9, 0x32,
	0x6d, 0xdb, 0xbc, 0x02, 0x00, 0x00, 0xff, 0xff, 0x6d, 0x78, 0x56, 0x12, 0xe9, 0x00, 0x00, 0x00,
}
