// Code generated by protoc-gen-go. DO NOT EDIT.
// source: tool.proto

package pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type DbInfo struct {
	Name     string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Ip       string `protobuf:"bytes,2,opt,name=ip" json:"ip,omitempty"`
	Port     int32  `protobuf:"varint,3,opt,name=port" json:"port,omitempty"`
	UserName string `protobuf:"bytes,4,opt,name=userName" json:"userName,omitempty"`
	Password string `protobuf:"bytes,5,opt,name=password" json:"password,omitempty"`
	Id       int64  `protobuf:"varint,6,opt,name=id" json:"id,omitempty"`
}

func (m *DbInfo) Reset()                    { *m = DbInfo{} }
func (m *DbInfo) String() string            { return proto.CompactTextString(m) }
func (*DbInfo) ProtoMessage()               {}
func (*DbInfo) Descriptor() ([]byte, []int) { return fileDescriptor4, []int{0} }

func (m *DbInfo) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *DbInfo) GetIp() string {
	if m != nil {
		return m.Ip
	}
	return ""
}

func (m *DbInfo) GetPort() int32 {
	if m != nil {
		return m.Port
	}
	return 0
}

func (m *DbInfo) GetUserName() string {
	if m != nil {
		return m.UserName
	}
	return ""
}

func (m *DbInfo) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *DbInfo) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

// 创建数据库
type CreateOrModifyReq struct {
	Db *DbInfo `protobuf:"bytes,1,opt,name=db" json:"db,omitempty"`
}

func (m *CreateOrModifyReq) Reset()                    { *m = CreateOrModifyReq{} }
func (m *CreateOrModifyReq) String() string            { return proto.CompactTextString(m) }
func (*CreateOrModifyReq) ProtoMessage()               {}
func (*CreateOrModifyReq) Descriptor() ([]byte, []int) { return fileDescriptor4, []int{1} }

func (m *CreateOrModifyReq) GetDb() *DbInfo {
	if m != nil {
		return m.Db
	}
	return nil
}

// 创建数据库
type CreateOrModifyRsp struct {
}

func (m *CreateOrModifyRsp) Reset()                    { *m = CreateOrModifyRsp{} }
func (m *CreateOrModifyRsp) String() string            { return proto.CompactTextString(m) }
func (*CreateOrModifyRsp) ProtoMessage()               {}
func (*CreateOrModifyRsp) Descriptor() ([]byte, []int) { return fileDescriptor4, []int{2} }

// 数据库详情
type DbDetailByIDReq struct {
	Id int64 `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
}

func (m *DbDetailByIDReq) Reset()                    { *m = DbDetailByIDReq{} }
func (m *DbDetailByIDReq) String() string            { return proto.CompactTextString(m) }
func (*DbDetailByIDReq) ProtoMessage()               {}
func (*DbDetailByIDReq) Descriptor() ([]byte, []int) { return fileDescriptor4, []int{3} }

func (m *DbDetailByIDReq) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type DbDetailByIDRsp struct {
	Db *DbInfo `protobuf:"bytes,1,opt,name=db" json:"db,omitempty"`
}

func (m *DbDetailByIDRsp) Reset()                    { *m = DbDetailByIDRsp{} }
func (m *DbDetailByIDRsp) String() string            { return proto.CompactTextString(m) }
func (*DbDetailByIDRsp) ProtoMessage()               {}
func (*DbDetailByIDRsp) Descriptor() ([]byte, []int) { return fileDescriptor4, []int{4} }

func (m *DbDetailByIDRsp) GetDb() *DbInfo {
	if m != nil {
		return m.Db
	}
	return nil
}

// 数据库分页
type DbPageReq struct {
	PageNo   int32 `protobuf:"varint,1,opt,name=pageNo" json:"pageNo,omitempty"`
	PageSize int32 `protobuf:"varint,2,opt,name=pageSize" json:"pageSize,omitempty"`
}

func (m *DbPageReq) Reset()                    { *m = DbPageReq{} }
func (m *DbPageReq) String() string            { return proto.CompactTextString(m) }
func (*DbPageReq) ProtoMessage()               {}
func (*DbPageReq) Descriptor() ([]byte, []int) { return fileDescriptor4, []int{5} }

func (m *DbPageReq) GetPageNo() int32 {
	if m != nil {
		return m.PageNo
	}
	return 0
}

func (m *DbPageReq) GetPageSize() int32 {
	if m != nil {
		return m.PageSize
	}
	return 0
}

// 数据库分页
type DbPageRsp struct {
	Dbs      []*DbInfo `protobuf:"bytes,1,rep,name=dbs" json:"dbs,omitempty"`
	PageNo   int32     `protobuf:"varint,2,opt,name=pageNo" json:"pageNo,omitempty"`
	PageSize int32     `protobuf:"varint,3,opt,name=pageSize" json:"pageSize,omitempty"`
	IsMore   int32     `protobuf:"varint,4,opt,name=isMore" json:"isMore,omitempty"`
}

func (m *DbPageRsp) Reset()                    { *m = DbPageRsp{} }
func (m *DbPageRsp) String() string            { return proto.CompactTextString(m) }
func (*DbPageRsp) ProtoMessage()               {}
func (*DbPageRsp) Descriptor() ([]byte, []int) { return fileDescriptor4, []int{6} }

func (m *DbPageRsp) GetDbs() []*DbInfo {
	if m != nil {
		return m.Dbs
	}
	return nil
}

func (m *DbPageRsp) GetPageNo() int32 {
	if m != nil {
		return m.PageNo
	}
	return 0
}

func (m *DbPageRsp) GetPageSize() int32 {
	if m != nil {
		return m.PageSize
	}
	return 0
}

func (m *DbPageRsp) GetIsMore() int32 {
	if m != nil {
		return m.IsMore
	}
	return 0
}

// 所有数据库
type AllNameReq struct {
}

func (m *AllNameReq) Reset()                    { *m = AllNameReq{} }
func (m *AllNameReq) String() string            { return proto.CompactTextString(m) }
func (*AllNameReq) ProtoMessage()               {}
func (*AllNameReq) Descriptor() ([]byte, []int) { return fileDescriptor4, []int{7} }

// 所有数据库
type AllNameRsp struct {
	Dbs []*DbInfo `protobuf:"bytes,1,rep,name=dbs" json:"dbs,omitempty"`
}

func (m *AllNameRsp) Reset()                    { *m = AllNameRsp{} }
func (m *AllNameRsp) String() string            { return proto.CompactTextString(m) }
func (*AllNameRsp) ProtoMessage()               {}
func (*AllNameRsp) Descriptor() ([]byte, []int) { return fileDescriptor4, []int{8} }

func (m *AllNameRsp) GetDbs() []*DbInfo {
	if m != nil {
		return m.Dbs
	}
	return nil
}

func init() {
	proto.RegisterType((*DbInfo)(nil), "pb.DbInfo")
	proto.RegisterType((*CreateOrModifyReq)(nil), "pb.CreateOrModifyReq")
	proto.RegisterType((*CreateOrModifyRsp)(nil), "pb.CreateOrModifyRsp")
	proto.RegisterType((*DbDetailByIDReq)(nil), "pb.DbDetailByIDReq")
	proto.RegisterType((*DbDetailByIDRsp)(nil), "pb.DbDetailByIDRsp")
	proto.RegisterType((*DbPageReq)(nil), "pb.DbPageReq")
	proto.RegisterType((*DbPageRsp)(nil), "pb.DbPageRsp")
	proto.RegisterType((*AllNameReq)(nil), "pb.AllNameReq")
	proto.RegisterType((*AllNameRsp)(nil), "pb.AllNameRsp")
}

func init() { proto.RegisterFile("tool.proto", fileDescriptor4) }

var fileDescriptor4 = []byte{
	// 310 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x92, 0xd1, 0x4a, 0xfb, 0x30,
	0x14, 0xc6, 0x49, 0xba, 0x96, 0xff, 0xce, 0x5f, 0x14, 0x23, 0x48, 0x18, 0x5e, 0xd4, 0x5c, 0x0d,
	0xc1, 0x09, 0xfa, 0x00, 0xa2, 0xf6, 0x66, 0x17, 0x9b, 0x12, 0x9f, 0x20, 0x21, 0x59, 0x09, 0xd4,
	0x25, 0x4b, 0x3a, 0x64, 0x3e, 0x81, 0x8f, 0x2d, 0x49, 0x67, 0xd5, 0x89, 0x7a, 0x97, 0x2f, 0xe7,
	0x3b, 0xbf, 0xef, 0xf4, 0x34, 0x00, 0xad, 0xb5, 0xcd, 0xc4, 0x79, 0xdb, 0x5a, 0x82, 0x9d, 0x64,
	0xaf, 0x08, 0x8a, 0x4a, 0x4e, 0x97, 0x0b, 0x4b, 0x08, 0x0c, 0x96, 0xe2, 0x49, 0x53, 0x54, 0xa2,
	0xf1, 0x90, 0xa7, 0x33, 0xd9, 0x07, 0x6c, 0x1c, 0xc5, 0xe9, 0x06, 0x1b, 0x17, 0x3d, 0xce, 0xfa,
	0x96, 0x66, 0x25, 0x1a, 0xe7, 0x3c, 0x9d, 0xc9, 0x08, 0xfe, 0xad, 0x83, 0xf6, 0xf3, 0xd8, 0x3b,
	0x48, 0xce, 0x5e, 0xc7, 0x9a, 0x13, 0x21, 0x3c, 0x5b, 0xaf, 0x68, 0xde, 0xd5, 0xde, 0x75, 0x62,
	0x2b, 0x5a, 0x94, 0x68, 0x9c, 0x71, 0x6c, 0x14, 0xbb, 0x80, 0xc3, 0x3b, 0xaf, 0x45, 0xab, 0xef,
	0xfd, 0xcc, 0x2a, 0xb3, 0xd8, 0x70, 0xbd, 0x22, 0x23, 0xc0, 0x4a, 0xa6, 0x91, 0xfe, 0x5f, 0xc2,
	0xc4, 0xc9, 0x49, 0x37, 0x2c, 0xc7, 0x4a, 0xb2, 0xa3, 0x6f, 0x0d, 0xc1, 0xb1, 0x53, 0x38, 0xa8,
	0x64, 0xa5, 0x5b, 0x61, 0x9a, 0xdb, 0xcd, 0xb4, 0x8a, 0x8c, 0x2e, 0x08, 0xf5, 0x41, 0xe7, 0x3b,
	0x96, 0xe0, 0x7e, 0x8d, 0xb9, 0x86, 0x61, 0x25, 0x1f, 0x44, 0xad, 0x23, 0xeb, 0x18, 0x0a, 0x27,
	0x6a, 0x3d, 0xb7, 0xc9, 0x9c, 0xf3, 0xad, 0xea, 0x3e, 0xb4, 0xd6, 0x8f, 0xe6, 0x45, 0xa7, 0x75,
	0xe5, 0xbc, 0xd7, 0x6c, 0xdd, 0x03, 0x82, 0x23, 0x27, 0x90, 0x29, 0x19, 0x28, 0x2a, 0xb3, 0x9d,
	0xa8, 0x78, 0xfd, 0x09, 0x8f, 0x7f, 0xc4, 0x67, 0x5f, 0xf1, 0xb1, 0xc7, 0x84, 0x99, 0xf5, 0xdd,
	0xf6, 0x73, 0xbe, 0x55, 0x6c, 0x0f, 0xe0, 0xa6, 0x69, 0xe2, 0x6f, 0xe0, 0x7a, 0xc5, 0xce, 0x3e,
	0xd4, 0x5f, 0x53, 0xc8, 0x22, 0xbd, 0x8f, 0xab, 0xb7, 0x00, 0x00, 0x00, 0xff, 0xff, 0xa3, 0x86,
	0x90, 0xb2, 0x2d, 0x02, 0x00, 0x00,
}
